alt for img tags
Codooze/Portfolio_2.github.io pull request #13
Opened 2023-06-12 23:36 UTC by Mehr-o-maah

# Milestone VI
- Worked on accessibility, covering the next points:

- [ ] Page titles  - no issues found
- [ ] Image text alternatives** (<img alt="alt text">)
- [ ] Text headings  - no issues found
- [ ] Color contrast  - no issues found
- [ ] Resize  - no issues found
- [ ] Moving content  - no issues found
- [ ] Multimedia  - no issues found
- [ ] The basic structure of the page  - no issues found

2023-06-12 23:45 UTC, Shedrack-Sunday requested changes
Hi @Mehr-o-maah  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that does not have your partners commit to the codebase as its a pair programming activity

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-13 14:43 UTC, Mehr-o-maah commented on index.html
> +          />
please use pair programming for this milestone

2023-06-13 14:44 UTC, Mehr-o-maah reviewed
testing

2023-06-13 14:44 UTC, Mehr-o-maah commented on index.html
> +            alt="Project preview image"
pair

2023-06-16 12:58 UTC, merged